Repository 3babko5/babko, pull requests merged in 2025-03, with the labels that each got.

#4 init : 프로젝트 초기 설정
  .gitattributes
  .gitignore
  ai/build.gradle
  ai/src/main/java/com/business/ai/AiApplication.java
  ai/src/main/java/com/business/ai/presentation/AiController.java
  ai/src/main/resources/application.yml
  ai/src/test/java/com/business/ai/AiApplicationTests.java
  build.gradle
  company/build.gradle
  company/src/main/java/com/business/company/CompanyApplication.java
  company/src/main/java/com/business/company/presentation/CompanyController.java
  company/src/main/resources/application.yml
  company/src/test/java/com/business/company/CompanyApplicationTests.java
  delivery/build.gradle
  delivery/src/main/java/com/business/delivery/DeliveryApplication.java
  delivery/src/main/java/com/business/delivery/presentation/DeliveryController.java
  delivery/src/main/resources/application.yml
  delivery/src/test/java/com/business/delivery/DeliveryApplicationTests.java
  eureka/build.gradle
  eureka/src/main/java/com/business/eureka/EurekaApplication.java
  eureka/src/main/resources/application.yml
  eureka/src/test/java/com/business/eureka/EurekaApplicationTests.java
  gateway/build.gradle
  gateway/src/main/java/com/business/gateway/GatewayApplication.java
  gateway/src/main/resources/application.yml
  gateway/src/test/java/com/business/gateway/GatewayApplicationTests.java
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  hub/build.gradle
  hub/src/main/java/com/business/hub/HubApplication.java
  hub/src/main/java/com/business/hub/presentation/HubController.java
  hub/src/main/resources/application.yml
  hub/src/test/java/com/business/hub/HubApplicationTests.java
  order/build.gradle
  order/src/main/java/com/business/order/OrderApplication.java
  order/src/main/java/com/business/order/presentation/OrderController.java
  order/src/main/resources/application.yml
  order/src/test/java/com/business/order/OrderApplicationTests.java
  product/build.gradle
  product/src/main/java/com/business/product/ProductApplication.java
  product/src/main/java/com/business/product/presentation/ProductController.java
  product/src/main/resources/application.yml
  product/src/test/java/com/business/product/ProductApplicationTests.java
  settings.gradle
  slack/build.gradle
  slack/src/main/java/com/business/slack/SlackApplication.java
  slack/src/main/java/com/business/slack/presentation/SlackController.java
  slack/src/main/resources/application.yml
  slack/src/test/java/com/business/slack/SlackApplicationTests.java
  src/main/java/com/business/babko/BabkoApplication.java
  src/main/resources/application.properties
  src/test/java/com/business/babko/BabkoApplicationTests.java
  user/build.gradle
  user/src/main/java/com/business/user/UserApplication.java
  user/src/main/java/com/business/user/presentation/UserController.java
  user/src/main/resources/application.yml
  user/src/test/java/com/business/user/UserApplicationTests.java
Labels: 🎉 init

#18 init: Gateway 마이크로 서비스 초기 의존성 설정
  .gitignore
  gateway/build.gradle
Labels: 🎉 init

#19 feat : auth, common 서브 모듈 추가 및 루트 모듈 src 제거
  auth/build.gradle
  auth/src/main/java/com/business/auth/AuthApplication.java
  auth/src/main/java/com/business/auth/presentation/AuthController.java
  auth/src/main/resources/application.yml
  auth/src/test/java/com/business/auth/AuthApplicationTests.java
  common/build.gradle
  common/src/main/java/com/business/common/CommonApplication.java
  common/src/main/java/com/business/common/presentation/CommonController.java
  common/src/main/resources/application.yml
  common/src/test/java/com/business/common/CommonApplicationTests.java
  gateway/src/main/resources/application.yml
  hub/build.gradle
  settings.gradle
  src/main/resources/application.properties
Labels: ✨ feat, 🔥 del

#20 feat : docker-compose 작성 및 도커 파일 생성
  ai/Dockerfile
  ai/build.gradle
  ai/src/main/resources/application.yml
  auth/Dockerfile
  auth/build.gradle
  auth/src/main/resources/application.yml
  build.gradle
  common/Dockerfile
  common/build.gradle
  common/src/main/resources/application.yml
  company/Dockerfile
  company/build.gradle
  company/src/main/resources/application.yml
  delivery/Dockerfile
  delivery/build.gradle
  delivery/src/main/resources/application.yml
  docker-compose.yml
  eureka/Dockerfile
  eureka/build.gradle
  gateway/Dockerfile
  gateway/build.gradle
  gateway/src/main/resources/application.yml
  hub/Dockerfile
  hub/build.gradle
  hub/src/main/resources/application.yml
  order/Dockerfile
  order/build.gradle
  order/src/main/resources/application.yml
  product/Dockerfile
  product/build.gradle
  product/src/main/resources/application.yml
  slack/Dockerfile
  slack/build.gradle
  slack/src/main/resources/application.yml
  user/Dockerfile
  user/build.gradle
  user/src/main/resources/application.yml
Labels: ✨ feat

#29 feat : 허브, 허브 이동 정보, 공통 Entitiy 설계
  hub/build.gradle
  hub/src/main/java/domain/entity/BaseEntity.java
  hub/src/main/java/domain/entity/Hub.java
  hub/src/main/java/domain/entity/HubMovement.java
Labels: ✨ feat

#30 feat: 배송 및 배송 경로 Entity 설계
  common/build.gradle
  delivery/src/main/java/com/business/delivery/domain/entity/Delivery.java
  delivery/src/main/java/com/business/delivery/domain/entity/DeliveryRoute.java
  delivery/src/main/java/com/business/delivery/domain/entity/DeliveryRouteStatus.java
  delivery/src/main/java/com/business/delivery/domain/entity/DeliveryStatus.java
  delivery/src/main/java/com/business/delivery/presentation/controller/DeliveryController.java
Labels: ✨ feat

#35 feat: company entity 생성
  company/src/main/java/com/business/company/domain/Company.java
  company/src/main/java/com/business/company/domain/CompanyType.java
Labels: ✨ feat

#47 feat: product, stock - entity, repository, dto, service 생성
  product/src/main/java/com/business/product/product/application/dto/request/ProductRequestDto.java
  product/src/main/java/com/business/product/product/application/dto/response/ProductResponseDto.java
  product/src/main/java/com/business/product/product/application/service/ProductService.java
  product/src/main/java/com/business/product/product/domain/entity/Product.java
  product/src/main/java/com/business/product/product/domain/repository/ProductRepository.java
  product/src/main/java/com/business/product/product/presentation/ProductController.java
  product/src/main/java/com/business/product/stock/application/dto/request/StockRequestDto.java
  product/src/main/java/com/business/product/stock/application/dto/response/StockResponseDto.java
  product/src/main/java/com/business/product/stock/application/service/StockService.java
  product/src/main/java/com/business/product/stock/domain/entity/Stock.java
  product/src/main/java/com/business/product/stock/domain/repository/StockRepository.java
  product/src/main/java/com/business/product/stock/presentation/StockController.java
Labels: ✨ feat

#61 feat: Auth common 모듈 적용
  auth/build.gradle
Labels: ✨ feat

#76 Bugfix: userId 타입 변경
  order/src/main/java/com/business/order/application/dto/request/OrderCreateRequestDto.java
  order/src/main/java/com/business/order/application/dto/request/OrderItemRequestDto.java
  order/src/main/java/com/business/order/application/dto/response/OrderCreateResponseDto.java
  order/src/main/java/com/business/order/application/dto/response/OrderItemResponseDto.java
  order/src/main/java/com/business/order/domain/entity/Order.java
  order/src/main/java/com/business/order/domain/entity/OrderItem.java
  order/src/main/java/com/business/order/infrastructure/dto/request/OrderDeliveryRequestDto.java
  order/src/main/java/com/business/order/infrastructure/dto/request/OrderDeliveryStatusRequestDto.java
  order/src/main/java/com/business/order/infrastructure/dto/response/OrderDeliveryStatusResponseDto.java
Labels: 🩹 fix

#77 feat: 배송 담당자 허브별 개수 제한 및 순번 관리 로직 추가
  common/build.gradle
  common/src/main/java/com/business/common/CommonApplication.java
  common/src/main/resources/application.yml
  delivery/src/main/java/com/business/delivery/DeliveryApplication.java
  delivery/src/main/java/com/business/delivery/infrastructure/client/HubMovementClient.java
  delivery/src/main/resources/application.yml
  hub/src/main/java/com/business/hub/domain/repository/HubRepository.java
  slack/src/main/java/com/business/slack/SlackApplication.java
  user/src/main/java/com/business/user/UserApplication.java
  user/src/main/java/com/business/user/application/exception/DeliveryDriverErrorCode.java
  user/src/main/java/com/business/user/application/service/DeliveryDriverService.java
  user/src/main/java/com/business/user/domain/repository/DeliveryDriverRepository.java
  user/src/main/java/com/business/user/infrastructure/client/HubClient.java
  user/src/main/java/com/business/user/infrastructure/client/HubClientService.java
  user/src/main/java/com/business/user/presentation/controller/DeliveryDriverController.java
  user/src/main/resources/application.yml
Labels: ✨ feat, ♻️ refactor

#85 feat: Common 모듈 적용 및 OpenFeign 설정 추가
  user/build.gradle
Labels: ✨ feat, 🎉 init

#86 feat: 네이버 Direction5 api 연결
  common/src/main/java/com/business/common/infrastructure/api/NaverApiService.java
Labels: ✨ feat

#91 fix: gitignore 수정
  .gitignore
  ai/src/main/resources/application.yml
  auth/src/main/resources/application.yml
  common/src/main/resources/application.yml
  company/src/main/resources/application.yml
  delivery/src/main/resources/application.yml
  docker-compose.yml
  eureka/src/main/resources/application.yml
  gateway/src/main/resources/application.yml
  hub/src/main/resources/application.yml
  order/src/main/resources/application.yml
  product/src/main/resources/application.yml
  slack/src/main/resources/application.yml
  user/src/main/resources/application.yml
Labels: 🩹 fix

#98 feat: 허브 간 이동 정보 등록 api 구현
  hub/src/main/java/com/business/hub/application/dto/request/HubMovementCreateRequest.java
  hub/src/main/java/com/business/hub/application/dto/response/HubMovementResponse.java
  hub/src/main/java/com/business/hub/application/mapper/HubMovementMapper.java
  hub/src/main/java/com/business/hub/application/service/HubMovementService.java
  hub/src/main/java/com/business/hub/domain/entity/HubMovement.java
  hub/src/main/java/com/business/hub/domain/repository/HubMovementRepository.java
  hub/src/main/java/com/business/hub/infrastructure/client/RouteNaverService.java
  hub/src/main/java/com/business/hub/infrastructure/repository/HubMovementJpaRepository.java
  hub/src/main/java/com/business/hub/infrastructure/repository/HubMovementRepositoryImpl.java
  hub/src/main/java/com/business/hub/presentation/HubMovementController.java
Labels: ✨ feat

#100 feat: 주문 생성 api 구현
  order/src/main/java/com/business/order/OrderApplication.java
  order/src/main/java/com/business/order/application/dto/request/OrderCreateRequestDto.java
  order/src/main/java/com/business/order/application/dto/request/OrderItemRequestDto.java
  order/src/main/java/com/business/order/application/dto/response/OrderCreateResponseDto.java
  order/src/main/java/com/business/order/application/dto/response/OrderItemResponseDto.java
  order/src/main/java/com/business/order/application/mapper/OrderMapper.java
  order/src/main/java/com/business/order/application/service/OrderService.java
  order/src/main/java/com/business/order/domain/entity/Order.java
  order/src/main/java/com/business/order/domain/entity/OrderItem.java
  order/src/main/java/com/business/order/domain/repository/OrderItemRepository.java
  order/src/main/java/com/business/order/domain/repository/OrderRepository.java
  order/src/main/java/com/business/order/infrastructure/dto/request/OrderDeliveryRequestDto.java
  order/src/main/java/com/business/order/infrastructure/repository/OrderItemJpaRepository.java
  order/src/main/java/com/business/order/infrastructure/repository/OrderItemRepositoryImpl.java
  order/src/main/java/com/business/order/infrastructure/repository/OrderJpaRepository.java
  order/src/main/java/com/business/order/infrastructure/repository/OrderRepositoryImpl.java
  order/src/main/java/com/business/order/presentaion/OrderController.java
Labels: ✨ feat

#115 fix: api 테스트 중 슬랙 아이디 null 문제 수정 / .http 파일 삭제
  user/src/main/java/com/business/user/application/dto/mapper/UserMapper.java
Labels: 🩹 fix, 🔥 del

#116 feat: company 생성 기능 구현
  company/src/main/java/com/business/company/CompanyApplication.java
  company/src/main/java/com/business/company/application/dto/request/CompanyRequestDto.java
  company/src/main/java/com/business/company/application/dto/request/CreateCompanyRequestDto.java
  company/src/main/java/com/business/company/application/dto/response/CompanyResponseDto.java
  company/src/main/java/com/business/company/application/dto/response/CreateCompanyResponseDto.java
  company/src/main/java/com/business/company/application/mapper/CompanyMapper.java
  company/src/main/java/com/business/company/application/service/CompanyService.java
  company/src/main/java/com/business/company/domain/entity/Company.java
  company/src/main/java/com/business/company/domain/repository/CompanyRepository.java
  company/src/main/java/com/business/company/infrastructure/repository/CompanyJpaRepository.java
  company/src/main/java/com/business/company/infrastructure/repository/CompanyRepositoryImpl.java
  company/src/main/java/com/business/company/presentation/CompanyController.java
Labels: ✨ feat

#125 bugfix: 오더 객체 무한루프 개선
  order/src/main/java/com/business/order/application/dto/request/OrderItemRequestDto.java
  order/src/main/java/com/business/order/application/dto/response/OrderCreateResponseDto.java
  order/src/main/java/com/business/order/application/dto/response/OrderItemResponseDto.java
  order/src/main/java/com/business/order/application/mapper/OrderMapper.java
  order/src/main/java/com/business/order/application/service/OrderService.java
  order/src/main/java/com/business/order/domain/entity/Order.java
  order/src/main/java/com/business/order/domain/entity/OrderItem.java
Labels: 🩹 fix, ♻️ refactor

#132 refactor: DDD 구조 적용
  delivery/src/main/java/com/business/delivery/application/service/DeliveryRouteService.java
  delivery/src/main/java/com/business/delivery/domain/repository/DeliveryRouteRepository.java
  delivery/src/main/java/com/business/delivery/infrastructure/repository/DeliveryRouteJpaRepository.java
  delivery/src/main/java/com/business/delivery/infrastructure/repository/DeliveryRouteRepositoryImpl.java
Labels: ✨ feat, ♻️ refactor

#134 test: 허브 수정 httpClient 테스트
  hub/src/test/resources/test/HubUpdateClient.http
Labels: 🍻 test

#129 feat: auth 서비스에 Dto, UserClient, UserType 추가
  auth/src/main/java/com/business/auth/application/dto/request/AuthSigninRequestDto.java
  auth/src/main/java/com/business/auth/application/dto/request/AuthSignupRequestDto.java
  auth/src/main/java/com/business/auth/application/dto/request/TokenRefreshRequestDto.java
  auth/src/main/java/com/business/auth/application/dto/response/AuthSigninResponseDto.java
  auth/src/main/java/com/business/auth/application/dto/response/AuthSignupResponseDto.java
  auth/src/main/java/com/business/auth/application/dto/response/TokenResponseDto.java
  auth/src/main/java/com/business/auth/domain/entity/UserType.java
  auth/src/main/java/com/business/auth/infrastructure/client/UserClient.java
Labels: ✨ feat

#131 feat: 허브 삭제 api 구현
  hub/src/main/java/com/business/hub/application/service/HubService.java
  hub/src/main/java/com/business/hub/presentation/HubController.java
Labels: ✨ feat

#138 feat: 허브 단일 조회, 전체 조회 api 구현
  hub/src/main/java/com/business/hub/application/dto/response/HubPageResponse.java
  hub/src/main/java/com/business/hub/application/service/HubService.java
  hub/src/main/java/com/business/hub/domain/repository/HubRepository.java
  hub/src/main/java/com/business/hub/infrastructure/repository/HubJpaRepository.java
  hub/src/main/java/com/business/hub/infrastructure/repository/HubRepositoryImpl.java
  hub/src/main/java/com/business/hub/presentation/HubController.java
  hub/src/test/resources/test/GetHubClient.http
Labels: ✨ feat

#141 feat: auth 서비스에 SecurityConfig JwtUtil 생성
  auth/build.gradle
  auth/src/main/java/com/business/auth/AuthApplication.java
  auth/src/main/java/com/business/auth/application/dto/request/AuthUserSignupRequestDto.java
  auth/src/main/java/com/business/auth/application/dto/response/AuthUserSigninResponseDto.java
  auth/src/main/java/com/business/auth/infrastructure/client/UserClient.java
  auth/src/main/java/com/business/auth/infrastructure/security/SecurityConfig.java
  auth/src/main/java/com/business/auth/infrastructure/util/JwtUtil.java
  common/src/main/java/com/business/common/infrastructure/api/NaverApiService.java
Labels: ✨ feat

#140 feat: 주문 생성 시 배송 요청을 수행하는 FeignClient 구현 및 리팩토링
  order/src/main/java/com/business/order/OrderApplication.java
  order/src/main/java/com/business/order/application/dto/mapper/OrderMapper.java
  order/src/main/java/com/business/order/application/dto/request/OrderCreateRequestDto.java
  order/src/main/java/com/business/order/application/dto/request/OrderItemRequestDto.java
  order/src/main/java/com/business/order/application/exception/OrderExceptionCode.java
  order/src/main/java/com/business/order/application/service/OrderService.java
  order/src/main/java/com/business/order/domain/entity/Order.java
  order/src/main/java/com/business/order/domain/entity/OrderItem.java
  order/src/main/java/com/business/order/domain/repository/OrderItemRepository.java
  order/src/main/java/com/business/order/infrastructure/client/DeliveryFeignClient.java
  order/src/main/java/com/business/order/infrastructure/dto/request/OrderDeliveryRequestDto.java
  order/src/main/java/com/business/order/infrastructure/dto/request/OrderDeliveryStatusRequestDto.java
  order/src/main/java/com/business/order/infrastructure/dto/response/OrderDeliveryStatusResponseDto.java
  order/src/main/java/com/business/order/infrastructure/repository/OrderItemJpaRepository.java
  order/src/main/java/com/business/order/infrastructure/repository/OrderItemRepositoryImpl.java
Labels: ✨ feat, ♻️ refactor

#145 feat: 허브 간 이동 정보 조회 api 구현
  hub/src/main/java/com/business/hub/application/dto/response/HubMovementPageResponse.java
  hub/src/main/java/com/business/hub/application/exception/HubExceptionCode.java
  hub/src/main/java/com/business/hub/application/service/HubMovementService.java
  hub/src/main/java/com/business/hub/domain/entity/HubMovement.java
  hub/src/main/java/com/business/hub/domain/repository/HubMovementRepository.java
  hub/src/main/java/com/business/hub/infrastructure/repository/HubMovementJpaRepository.java
  hub/src/main/java/com/business/hub/infrastructure/repository/HubMovementRepositoryImpl.java
  hub/src/main/java/com/business/hub/presentation/HubMovementController.java
  hub/src/test/resources/test/GetHubMovementClientTest.http
  hub/src/test/resources/test/HubMovementRegistertest.http
Labels: ✨ feat

#147 feat: company 조회 페이징 기능 추가
  company/build.gradle
  company/src/main/java/com/business/company/CompanyApplication.java
  company/src/main/java/com/business/company/application/dto/request/SearchCompanyRequestDto.java
  company/src/main/java/com/business/company/application/dto/response/SearchCompanyResponseDto.java
  company/src/main/java/com/business/company/application/mapper/CompanyMapper.java
  company/src/main/java/com/business/company/application/service/CompanyService.java
  company/src/main/java/com/business/company/domain/entity/Company.java
  company/src/main/java/com/business/company/domain/repository/CompanyRepository.java
  company/src/main/java/com/business/company/infrastructure/repository/CompanyJpaRepository.java
  company/src/main/java/com/business/company/infrastructure/repository/CompanyRepositoryImpl.java
  company/src/main/java/com/business/company/presentation/CompanyController.java
Labels: ✨ feat

#149 feat: 허브 간 이동 정보 수정, 삭제 api 구현
  hub/src/main/java/com/business/hub/application/dto/request/HubMovementUpdateRequest.java
  hub/src/main/java/com/business/hub/application/service/HubMovementService.java
  hub/src/main/java/com/business/hub/domain/entity/HubMovement.java
  hub/src/main/java/com/business/hub/presentation/HubMovementController.java
  hub/src/test/resources/test/GetHubMovementClientTest.http
  hub/src/test/resources/test/HubMovementDeleteTest.http
  hub/src/test/resources/test/HubMovementUpdateTest.http
Labels: ✨ feat, ♻️ refactor

#150 del: 배송과 배송 경로를 하나의 애그리거트로 통합
  delivery/src/main/java/com/business/delivery/application/dto/mapper/DeliveryRouteMapper.java
  delivery/src/main/java/com/business/delivery/application/dto/response/DeliveryRouteResponseDto.java
  delivery/src/main/java/com/business/delivery/application/service/DeliveryRouteService.java
  delivery/src/main/java/com/business/delivery/domain/repository/DeliveryRouteRepository.java
  delivery/src/main/java/com/business/delivery/infrastructure/repository/DeliveryRouteJpaRepository.java
  delivery/src/main/java/com/business/delivery/infrastructure/repository/DeliveryRouteRepositoryImpl.java
  delivery/src/main/java/com/business/delivery/presentation/controller/DeliveryRouteController.java
Labels: 🔥 del

#153 test: 주문 생성 테스트
  common/src/main/java/com/business/common/infrastructure/api/NaverApiService.java
  order/src/test/resources/test/CreateOrderClient.http
Labels: 🍻 test

#155 feat: product 생성 기능 구현
  product/src/main/java/com/business/product/ProductApplication.java
  product/src/main/java/com/business/product/product/application/dto/request/CreateProductRequestDto.java
  product/src/main/java/com/business/product/product/application/dto/request/ProductRequestDto.java
  product/src/main/java/com/business/product/product/application/dto/response/CreateProductResponseDto.java
  product/src/main/java/com/business/product/product/application/dto/response/ProductResponseDto.java
  product/src/main/java/com/business/product/product/application/mapper/ProductMapper.java
  product/src/main/java/com/business/product/product/application/service/ProductService.java
  product/src/main/java/com/business/product/product/domain/entity/Product.java
  product/src/main/java/com/business/product/product/domain/repository/ProductRepository.java
  product/src/main/java/com/business/product/product/infrastructure/repository/ProductJpaRepository.java
  product/src/main/java/com/business/product/product/infrastructure/repository/ProductRepositoryImpl.java
  product/src/main/java/com/business/product/product/presentation/ProductController.java
  product/src/main/java/com/business/product/stock/application/dto/request/StockRequestDto.java
  product/src/main/java/com/business/product/stock/application/dto/response/StockResponseDto.java
  product/src/main/java/com/business/product/stock/application/service/StockService.java
  product/src/main/java/com/business/product/stock/domain/entity/Stock.java
  product/src/main/java/com/business/product/stock/domain/repository/StockRepository.java
Labels: ✨ feat

#158 del: user 컴파일 에러 테스트 코드 삭제
  user/src/test/java/com/business/user/application/service/UserServiceTest.java
Labels: 🔥 del

#166 feat: ProductFeignClient 통신 기능 구현
  order/src/main/java/com/business/order/application/dto/request/OrderItemRequestDto.java
  order/src/main/java/com/business/order/application/exception/OrderExceptionCode.java
  order/src/main/java/com/business/order/application/service/OrderService.java
  order/src/main/java/com/business/order/infrastructure/client/DeliveryFeignClient.java
  order/src/main/java/com/business/order/infrastructure/client/ProductFeignClient.java
  order/src/main/java/com/business/order/infrastructure/dto/response/ProductDetailResponseDto.java
Labels: ✨ feat

#163 feat: 허브 간 이동 경로 조회 api 구현
  hub/src/main/java/com/business/hub/application/service/HubMovementService.java
  hub/src/main/java/com/business/hub/presentation/HubMovementController.java
  hub/src/test/resources/test/GetHubMovementClientTest.http
Labels: ✨ feat

#171 fix: DeliveryJpaRepository의 불필요한 custom save() 제거
  delivery/src/main/java/com/business/delivery/infrastructure/repository/DeliveryJpaRepository.java
  delivery/src/main/java/com/business/delivery/infrastructure/repository/DeliveryRepositoryImpl.java
Labels: 🩹 fix

#185 feat: 주문 취소 api 구현
  order/src/main/java/com/business/order/application/dto/mapper/OrderMapper.java
  order/src/main/java/com/business/order/application/dto/response/OrderStatusResponseDto.java
  order/src/main/java/com/business/order/application/exception/OrderExceptionCode.java
  order/src/main/java/com/business/order/application/service/OrderService.java
  order/src/main/java/com/business/order/domain/entity/Order.java
  order/src/main/java/com/business/order/domain/entity/OrderStatus.java
  order/src/main/java/com/business/order/domain/repository/OrderRepository.java
  order/src/main/java/com/business/order/infrastructure/client/DeliveryFeignClient.java
  order/src/main/java/com/business/order/infrastructure/repository/OrderJpaRepository.java
  order/src/main/java/com/business/order/infrastructure/repository/OrderRepositoryImpl.java
  order/src/main/java/com/business/order/presentaion/OrderController.java
  order/src/test/resources/test/CancelOrderClient.http
Labels: ✨ feat, 🍻 test

#195 feat: 배송 전체 조회 API 구현
  delivery/build.gradle
  delivery/src/main/java/com/business/delivery/application/dto/mapper/DeliveryMapper.java
  delivery/src/main/java/com/business/delivery/application/dto/mapper/DeliveryRequestMapper.java
  delivery/src/main/java/com/business/delivery/application/dto/mapper/DeliveryResponseMapper.java
  delivery/src/main/java/com/business/delivery/application/dto/request/DeliverySearchRequestDto.java
  delivery/src/main/java/com/business/delivery/application/dto/response/DeliveryPageResponseDto.java
  delivery/src/main/java/com/business/delivery/application/dto/response/DeliveryPageWrapperResponseDto.java
  delivery/src/main/java/com/business/delivery/application/service/DeliveryService.java
  delivery/src/main/java/com/business/delivery/domain/entity/Delivery.java
  delivery/src/main/java/com/business/delivery/domain/entity/DeliveryRoute.java
  delivery/src/main/java/com/business/delivery/domain/repository/DeliveryRepository.java
  delivery/src/main/java/com/business/delivery/infrastructure/client/UserClient.java
  delivery/src/main/java/com/business/delivery/infrastructure/repository/DeliveryRepositoryImpl.java
  delivery/src/main/java/com/business/delivery/presentation/controller/DeliveryController.java
Labels: 🎈 feat

#196 feat: 허브 검색 api 구현
  hub/build.gradle
  hub/src/main/java/com/business/hub/application/dto/request/HubSearchRequest.java
  hub/src/main/java/com/business/hub/application/mapper/HubMapper.java
  hub/src/main/java/com/business/hub/application/service/HubService.java
  hub/src/main/java/com/business/hub/domain/entity/Hub.java
  hub/src/main/java/com/business/hub/domain/repository/HubQueryDslRepository.java
  hub/src/main/java/com/business/hub/domain/repository/HubRepository.java
  hub/src/main/java/com/business/hub/infrastructure/repository/HubJpaRepository.java
  hub/src/main/java/com/business/hub/infrastructure/repository/HubRepositoryImpl.java
  hub/src/main/java/com/business/hub/presentation/HubController.java
  hub/src/test/resources/test/HubSearchTest.http
Labels: 🎈 feat, 🌼 test

#198 feat: 배송 상세 조회 API 구현
  delivery/src/main/java/com/business/delivery/application/dto/mapper/DeliveryResponseMapper.java
  delivery/src/main/java/com/business/delivery/application/dto/response/DeliveryDetailResponseDto.java
  delivery/src/main/java/com/business/delivery/application/dto/response/DeliveryPageListResponseDto.java
  delivery/src/main/java/com/business/delivery/application/dto/response/DeliveryPageWrapperResponseDto.java
  delivery/src/main/java/com/business/delivery/application/exception/DeliveryErrorCode.java
  delivery/src/main/java/com/business/delivery/application/service/DeliveryService.java
  delivery/src/main/java/com/business/delivery/domain/repository/DeliveryRepository.java
  delivery/src/main/java/com/business/delivery/infrastructure/client/OrderClient.java
  delivery/src/main/java/com/business/delivery/infrastructure/dto/response/OrderInfoResponseDto.java
  delivery/src/main/java/com/business/delivery/infrastructure/repository/DeliveryRepositoryImpl.java
  delivery/src/main/java/com/business/delivery/presentation/controller/DeliveryController.java
Labels: 🎈 feat

#197 feat: 주문 생성을 위한 CompanyFeignClient 통신 구현
  order/src/main/java/com/business/order/application/exception/OrderExceptionCode.java
  order/src/main/java/com/business/order/application/service/OrderService.java
  order/src/main/java/com/business/order/domain/entity/CompanyType.java
  order/src/main/java/com/business/order/infrastructure/client/CompanyFeignClient.java
  order/src/main/java/com/business/order/infrastructure/dto/response/hubIdResponseDto.java
Labels: 🎈 feat

#201 feat: 배송 담당자 전체 조회 API 구현
  delivery/build.gradle
  user/build.gradle
  user/src/main/java/com/business/user/deliverydriver/application/dto/mapper/DeliveryDriverRequestMapper.java
  user/src/main/java/com/business/user/deliverydriver/application/dto/mapper/DeliveryDriverResponseMapper.java
  user/src/main/java/com/business/user/deliverydriver/application/dto/request/DeliveryDriverSearchRequestDto.java
  user/src/main/java/com/business/user/deliverydriver/application/dto/response/DeliveryDriverListResponseDto.java
  user/src/main/java/com/business/user/deliverydriver/application/dto/response/DeliveryDriverPageResponseDto.java
  user/src/main/java/com/business/user/deliverydriver/application/service/DeliveryDriverService.java
  user/src/main/java/com/business/user/deliverydriver/domain/repository/DeliveryDriverRepository.java
  user/src/main/java/com/business/user/deliverydriver/infrastructure/repository/DeliveryDriverRepositoryImpl.java
  user/src/main/java/com/business/user/deliverydriver/presentation/controller/DeliveryDriverController.java
Labels: 🎈 feat

#204 refactor: 업체, 상품 Controller 리팩토링
  company/src/main/java/com/business/company/application/dto/request/SearchCompanyRequestDto.java
  company/src/main/java/com/business/company/presentation/CompanyController.java
  product/src/main/java/com/business/product/inventory/presentation/InventoryController.java
  product/src/main/java/com/business/product/product/application/dto/request/SearchProductRequestDto.java
  product/src/main/java/com/business/product/product/presentation/ProductController.java
Labels: ♻️ refactor

#207 fix: ProductRepositoryImpl 수정
  product/src/main/java/com/business/product/product/infrastructure/repository/ProductRepositoryImpl.java
Labels: 🩹 fix

#209 fix: Search 시 정렬 기준 기본값 적용
  company/src/main/java/com/business/company/application/dto/request/SearchCompanyRequestDto.java
  product/src/main/java/com/business/product/product/application/dto/request/SearchProductRequestDto.java
Labels: 🩹 fix

#182 feat: Auth 회원가입, 로그인, 토큰 재발급, JWT, SecurityConfig, UserServiceClient
  auth/build.gradle
  auth/src/main/java/com/business/auth/AuthApplication.java
  auth/src/main/java/com/business/auth/application/dto/request/AuthSigninRequestDto.java
  auth/src/main/java/com/business/auth/application/dto/request/AuthUserSignupRequestDto.java
  auth/src/main/java/com/business/auth/application/dto/request/LoginRequestDto.java
  auth/src/main/java/com/business/auth/application/dto/request/SignupRequestDto.java
  auth/src/main/java/com/business/auth/application/dto/request/TokenRefreshRequestDto.java
  auth/src/main/java/com/business/auth/application/dto/response/AuthSignupResponseDto.java
  auth/src/main/java/com/business/auth/application/dto/response/AuthUserSigninResponseDto.java
  auth/src/main/java/com/business/auth/application/dto/response/JwtTokenResponseDto.java
  auth/src/main/java/com/business/auth/application/exception/AuthExceptionCode.java
  auth/src/main/java/com/business/auth/application/service/AuthService.java
  auth/src/main/java/com/business/auth/domain/entity/Token.java
  auth/src/main/java/com/business/auth/domain/entity/UserType.java
  auth/src/main/java/com/business/auth/domain/repository/TokenRepository.java
  auth/src/main/java/com/business/auth/infrastructure/client/UserClient.java
  auth/src/main/java/com/business/auth/infrastructure/client/dto/CreateUserRequest.java
  auth/src/main/java/com/business/auth/infrastructure/client/dto/UserResponse.java
  auth/src/main/java/com/business/auth/infrastructure/config/JwtTokenProvider.java
  auth/src/main/java/com/business/auth/infrastructure/config/SecurityConfig.java
  auth/src/main/java/com/business/auth/infrastructure/dto/request/UserCreateRequestDto.java
  auth/src/main/java/com/business/auth/infrastructure/dto/response/UserCreateResponseDto.java
  auth/src/main/java/com/business/auth/infrastructure/security/SecurityConfig.java
  auth/src/main/java/com/business/auth/infrastructure/util/JwtTokenUtil.java
  auth/src/main/java/com/business/auth/presentation/AuthController.java
  auth/src/main/java/com/business/auth/presentation/controller/AuthController.java
  auth/src/test/java/com/business/auth/application/service/AuthServiceTest.java
  common/src/main/java/com/business/common/aop/RoleCheck.java
  common/src/main/java/com/business/common/aop/RoleCheckAspect.java
  deploy.sh
  gateway/build.gradle
  gateway/src/main/java/com/business/gateway/GatewayApplication.java
  gateway/src/main/java/com/business/gateway/config/RouterConfig.java
  gateway/src/main/java/com/business/gateway/filter/JwtFilter.java
  gateway/src/main/java/com/business/gateway/jwt/JwtUtil.java
  gradlew
  user/src/main/java/com/business/user/UserApplication.java
  user/src/main/java/com/business/user/user/application/dto/mapper/UserMapper.java
  user/src/main/java/com/business/user/user/application/exception/UserExceptionCode.java
  user/src/main/java/com/business/user/user/application/service/UserService.java
  user/src/main/java/com/business/user/user/domain/dto/CreateUserRequestDto.java
  user/src/main/java/com/business/user/user/domain/dto/UserResponseDto.java
  user/src/main/java/com/business/user/user/domain/repository/UserRepository.java
  user/src/main/java/com/business/user/user/presentation/controller/UserController.java
Labels: 🎈 feat, 🩹 fix, 🌼 test

#211 Feat: 배송 담당자 상세 조회 API 구현
  delivery/src/main/java/com/business/delivery/infrastructure/client/UserClient.java
  delivery/src/main/java/com/business/delivery/infrastructure/repository/DeliveryRepositoryImpl.java
  user/build.gradle
  user/src/main/java/com/business/user/deliverydriver/application/dto/mapper/DeliveryDriverResponseMapper.java
  user/src/main/java/com/business/user/deliverydriver/application/dto/response/DeliveryDriverDetailResponseDto.java
  user/src/main/java/com/business/user/deliverydriver/application/dto/response/DeliveryDriverRouteResponseDto.java
  user/src/main/java/com/business/user/deliverydriver/application/exception/DeliveryDriverErrorCode.java
  user/src/main/java/com/business/user/deliverydriver/application/service/DeliveryDriverService.java
  user/src/main/java/com/business/user/deliverydriver/domain/repository/DeliveryDriverRepository.java
  user/src/main/java/com/business/user/deliverydriver/infrastructure/dto/response/DeliveryClientResponseDto.java
  user/src/main/java/com/business/user/deliverydriver/infrastructure/repository/DeliveryDriverJpaRepository.java
  user/src/main/java/com/business/user/deliverydriver/infrastructure/repository/DeliveryDriverRepositoryImpl.java
  user/src/main/java/com/business/user/deliverydriver/presentation/controller/DeliveryDriverController.java
  user/src/test/java/com/business/user/deliverydriver/infrastructure/repository/DeliveryDriverRepositoryTest.java
Labels: 🎈 feat, ♻️ refactor

#217 feat: 주문 취소 시 배송 취소 요청
  order/src/main/java/com/business/order/application/exception/OrderExceptionCode.java
  order/src/main/java/com/business/order/application/service/OrderService.java
  order/src/main/java/com/business/order/domain/entity/Order.java
  order/src/main/java/com/business/order/domain/repository/OrderRepository.java
  order/src/main/java/com/business/order/infrastructure/client/DeliveryFeignClient.java
  order/src/main/java/com/business/order/infrastructure/dto/response/DeliveryIdResponseDto.java
  order/src/main/java/com/business/order/infrastructure/repository/OrderRepositoryImpl.java
Labels: 🎈 feat

#219 feat: 허브 삭제 시 관련 허브 간 이동 정보 삭제
  hub/src/main/java/com/business/hub/application/service/HubService.java
Labels: 🎈 feat

#222 fix: baseEntity 메서드 수정
  auth/src/main/java/com/business/auth/application/service/AuthService.java
  auth/src/main/java/com/business/auth/domain/entity/Token.java
  company/src/main/java/com/business/company/application/dto/request/SearchCompanyRequestDto.java
  hub/src/main/java/com/business/hub/application/service/HubService.java
  user/src/main/java/com/business/user/deliverydriver/presentation/controller/DeliveryDriverController.java
  user/src/main/java/com/business/user/user/application/service/UserService.java
  user/src/test/java/com/business/user/deliverydriver/infrastructure/repository/DeliveryDriverRepositoryTest.java
Labels: 🩹 fix

#228 feat: 업체 삭제 기능 구현, 상품 수량 및 재고 제약 조건 추가
  company/src/main/java/com/business/company/application/service/CompanyService.java
  company/src/main/java/com/business/company/domain/entity/Company.java
  company/src/main/java/com/business/company/domain/repository/CompanyRepository.java
  company/src/main/java/com/business/company/infrastructure/repository/CompanyJpaRepository.java
  company/src/main/java/com/business/company/infrastructure/repository/CompanyRepositoryImpl.java
  company/src/main/java/com/business/company/presentation/CompanyController.java
  company/src/test/resources/test/DeleteCompany.http
  product/src/main/java/com/business/product/product/domain/entity/Product.java
Labels: 🎈 feat

#239 Feat: 배송 및 배송 담당자 취소 API 구현
  delivery/src/main/java/com/business/delivery/application/exception/DeliveryErrorCode.java
  delivery/src/main/java/com/business/delivery/application/service/DeliveryService.java
  delivery/src/main/java/com/business/delivery/domain/entity/Delivery.java
  delivery/src/main/java/com/business/delivery/domain/entity/DeliveryRoute.java
  delivery/src/main/java/com/business/delivery/domain/entity/DeliveryRouteStatus.java
  delivery/src/main/java/com/business/delivery/domain/entity/DeliveryStatus.java
  delivery/src/main/java/com/business/delivery/infrastructure/client/UserClient.java
  delivery/src/main/java/com/business/delivery/presentation/controller/DeliveryController.java
  delivery/src/test/java/com/business/delivery/application/service/DeliveryServiceTest.java
  delivery/src/test/java/com/business/delivery/infrastructure/client/MockUserClient.java
  user/src/main/java/com/business/user/deliverydriver/application/exception/DeliveryDriverErrorCode.java
  user/src/main/java/com/business/user/deliverydriver/application/service/DeliveryDriverService.java
  user/src/main/java/com/business/user/deliverydriver/domain/entity/DeliveryDriver.java
  user/src/main/java/com/business/user/deliverydriver/domain/entity/DriverStatus.java
  user/src/main/java/com/business/user/deliverydriver/domain/repository/DeliveryDriverRepository.java
  user/src/main/java/com/business/user/deliverydriver/infrastructure/client/DeliveryClient.java
  user/src/main/java/com/business/user/deliverydriver/infrastructure/repository/DeliveryDriverJpaRepository.java
  user/src/main/java/com/business/user/deliverydriver/infrastructure/repository/DeliveryDriverRepositoryImpl.java
  user/src/main/java/com/business/user/deliverydriver/presentation/controller/DeliveryDriverController.java
  user/src/test/java/com/business/user/deliverydriver/application/service/DeliveryDriverServiceTest.java
Labels: 🎈 feat, 🌼 test

#241 fix : auth user gateway 전체적인 부분 수정
  auth/src/main/java/com/business/auth/AuthApplication.java
  auth/src/main/java/com/business/auth/application/dto/request/SignupRequestDto.java
  auth/src/main/java/com/business/auth/application/dto/response/JwtTokenResponseDto.java
  auth/src/main/java/com/business/auth/application/service/AuthService.java
  auth/src/main/java/com/business/auth/infrastructure/client/UserClient.java
  auth/src/main/java/com/business/auth/infrastructure/config/JwtTokenProvider.java
  auth/src/main/java/com/business/auth/infrastructure/dto/UserResponse.java
  auth/src/main/java/com/business/auth/infrastructure/dto/request/CreateUserRequest.java
  auth/src/main/java/com/business/auth/infrastructure/dto/request/UserCreateRequestDto.java
  auth/src/main/java/com/business/auth/infrastructure/dto/response/UserCreateResponseDto.java
  auth/src/main/java/com/business/auth/presentation/controller/AuthController.java
  deploy.sh
  gateway/build.gradle
  gateway/src/main/java/com/business/gateway/config/RouterConfig.java
  gateway/src/main/java/com/business/gateway/filter/JwtFilter.java
  gateway/src/main/java/com/business/gateway/jwt/JwtUtil.java
  user/src/main/java/com/business/user/UserApplication.java
  user/src/main/java/com/business/user/user/application/dto/request/CreateUserRequestDto.java
  user/src/main/java/com/business/user/user/application/dto/request/UserSearchRequestDto.java
  user/src/main/java/com/business/user/user/application/dto/request/UserSignupRequestDto.java
  user/src/main/java/com/business/user/user/application/dto/request/UserUpdateRequestDto.java
  user/src/main/java/com/business/user/user/application/dto/response/UserDetailResponseDto.java
  user/src/main/java/com/business/user/user/application/dto/response/UserPageResponseDto.java
  user/src/main/java/com/business/user/user/application/dto/response/UserResponseDto.java
  user/src/main/java/com/business/user/user/application/dto/response/UserSigninResponseDto.java
  user/src/main/java/com/business/user/user/application/dto/response/UserSignupResponseDto.java
  user/src/main/java/com/business/user/user/application/mapper/UserMapper.java
  user/src/main/java/com/business/user/user/application/service/UserService.java
  user/src/main/java/com/business/user/user/domain/dto/UserResponseDto.java
  user/src/main/java/com/business/user/user/domain/entity/User.java
  user/src/main/java/com/business/user/user/domain/repository/UserRepository.java
  user/src/main/java/com/business/user/user/infrastructure/client/AuthClient.java
  user/src/main/java/com/business/user/user/presentation/controller/UserController.java
Labels: 🩹 fix

#240 bugfix: 주문 서비스에서 상품/업체/배송 서비스와 통신 구조 수정
  order/src/main/java/com/business/order/application/dto/mapper/DeliveryMapper.java
  order/src/main/java/com/business/order/application/dto/mapper/OrderMapper.java
  order/src/main/java/com/business/order/application/dto/mapper/RequestMapper.java
  order/src/main/java/com/business/order/application/dto/response/ProductDetailResponseDto.java
  order/src/main/java/com/business/order/application/dto/response/hubIdResponseDto.java
  order/src/main/java/com/business/order/application/exception/OrderExceptionCode.java
  order/src/main/java/com/business/order/application/service/OrderService.java
  order/src/main/java/com/business/order/domain/entity/DeliveryStatus.java
  order/src/main/java/com/business/order/infrastructure/client/CompanyFeignClient.java
  order/src/main/java/com/business/order/infrastructure/client/DeliveryFeignClient.java
  order/src/main/java/com/business/order/infrastructure/client/ProductFeignClient.java
  order/src/main/java/com/business/order/infrastructure/dto/queryDto/SearchCompanyQueryDto.java
  order/src/main/java/com/business/order/infrastructure/dto/queryDto/SearchProductQueryDto.java
  order/src/main/java/com/business/order/infrastructure/dto/request/CreateDeliveryRequestDto.java
  order/src/main/java/com/business/order/infrastructure/dto/request/OrderDeliveryRequestDto.java
  order/src/main/java/com/business/order/infrastructure/dto/response/GetCompanyInfoResponseDto.java
  order/src/main/java/com/business/order/infrastructure/dto/response/GetDeliveryCreateResponseDto.java
  order/src/main/java/com/business/order/infrastructure/dto/response/GetProductInfoResponseDto.java
  order/src/test/resources/test/CreateOrderClient.http
Labels: 🩹 fix

#244 feat: 배송, 배송 담당자 상태 변경 API 구현
  delivery/src/main/java/com/business/delivery/application/dto/mapper/DeliveryRequestMapper.java
  delivery/src/main/java/com/business/delivery/application/dto/mapper/DeliveryResponseMapper.java
  delivery/src/main/java/com/business/delivery/application/dto/request/SearchRequestDto.java
  delivery/src/main/java/com/business/delivery/application/dto/request/StatusUpdateRequestDto.java
  delivery/src/main/java/com/business/delivery/application/dto/response/DeliveryStatusUpdateResponseDto.java
  delivery/src/main/java/com/business/delivery/application/exception/DeliveryErrorCode.java
  delivery/src/main/java/com/business/delivery/application/service/DeliveryService.java
  delivery/src/main/java/com/business/delivery/domain/entity/Delivery.java
  delivery/src/main/java/com/business/delivery/domain/entity/DeliveryRoute.java
  delivery/src/main/java/com/business/delivery/domain/entity/DeliveryRouteStatus.java
  delivery/src/main/java/com/business/delivery/domain/entity/DeliveryStatus.java
  delivery/src/main/java/com/business/delivery/domain/repository/DeliveryRepository.java
  delivery/src/main/java/com/business/delivery/infrastructure/client/OrderClient.java
  delivery/src/main/java/com/business/delivery/infrastructure/client/UserClient.java
  delivery/src/main/java/com/business/delivery/infrastructure/repository/DeliveryRepositoryImpl.java
  delivery/src/main/java/com/business/delivery/presentation/controller/DeliveryController.java
  delivery/src/test/java/com/business/delivery/application/service/DeliveryServiceCancelTest.java
  delivery/src/test/java/com/business/delivery/application/service/DeliveryServiceStatusTest.java
  delivery/src/test/java/com/business/delivery/infrastructure/client/MockOrderClient.java
  user/src/main/java/com/business/user/deliverydriver/application/dto/mapper/DeliveryDriverResponseMapper.java
  user/src/main/java/com/business/user/deliverydriver/application/dto/request/StatusUpdateRequestDto.java
  user/src/main/java/com/business/user/deliverydriver/application/dto/response/DriverStatusUpdateResponseDto.java
  user/src/main/java/com/business/user/deliverydriver/application/exception/DeliveryDriverErrorCode.java
  user/src/main/java/com/business/user/deliverydriver/application/service/DeliveryDriverService.java
  user/src/main/java/com/business/user/deliverydriver/domain/entity/DeliveryDriver.java
  user/src/main/java/com/business/user/deliverydriver/domain/entity/DriverStatus.java
  user/src/main/java/com/business/user/deliverydriver/presentation/controller/DeliveryDriverController.java
  user/src/test/java/com/business/user/deliverydriver/application/service/DeliveryDriverServiceCancelTest.java
  user/src/test/java/com/business/user/deliverydriver/application/service/DeliveryDriverServiceStatusTest.java
  user/src/test/java/com/business/user/deliverydriver/infrastructure/repository/DeliveryDriverRepositoryTest.java
Labels: 🎈 feat, 🌼 test

#248 feat: 주문 상태를 변경하는 api 구현 (주문 완료, 주문 취소 api 추가)
  order/src/main/java/com/business/order/application/dto/response/DeliveryStatusForOrderDto.java
  order/src/main/java/com/business/order/application/service/OrderService.java
  order/src/main/java/com/business/order/domain/entity/Order.java
  order/src/main/java/com/business/order/domain/entity/OrderStatus.java
  order/src/main/java/com/business/order/infrastructure/client/DeliveryFeignClient.java
  order/src/main/java/com/business/order/infrastructure/dto/request/DeliverySearchForOrderRequestDto.java
  order/src/main/java/com/business/order/infrastructure/dto/response/DeliveryListForOrderResponseDto.java
  order/src/main/java/com/business/order/presentaion/OrderController.java
  order/src/test/resources/test/CancelOrderClient.http
  order/src/test/resources/test/updateOrderClient.http
Labels: 🎈 feat

#250 fix: Delivery 저장 시 즉시 flush를 위한 saveAndFlush 메서드 추가
  delivery/src/main/java/com/business/delivery/application/service/DeliveryService.java
  delivery/src/main/java/com/business/delivery/domain/repository/DeliveryRepository.java
  delivery/src/main/java/com/business/delivery/infrastructure/repository/DeliveryRepositoryImpl.java
Labels: 🩹 fix

#249 feat: 허브 도메인 권한 인증 aop 추가
  hub/src/main/java/com/business/hub/application/service/HubMovementService.java
  hub/src/main/java/com/business/hub/application/service/HubService.java
  hub/src/main/java/com/business/hub/presentation/HubController.java
  hub/src/main/java/com/business/hub/presentation/HubMovementController.java
Labels: 🎈 feat

#253 feat: 주문 특정 검색 api 구현
  order/build.gradle
  order/src/main/java/com/business/order/application/dto/mapper/OrderMapper.java
  order/src/main/java/com/business/order/application/dto/request/SearchOrderRequestDto.java
  order/src/main/java/com/business/order/application/dto/response/SearchOrderResponseDto.java
  order/src/main/java/com/business/order/application/service/OrderService.java
  order/src/main/java/com/business/order/domain/repository/OrderRepository.java
  order/src/main/java/com/business/order/infrastructure/repository/OrderRepositoryImpl.java
  order/src/main/java/com/business/order/presentaion/OrderController.java
  order/src/test/resources/test/GetOrderClient.http
Labels: 🎈 feat

#264 docs: README 작성
  README.md
Labels: 📝 docs

#265 docs: README 작성
  README.md
Labels: 📝 docs

#266 fix : User 관련 API 및 서비스 수정"
  common/src/main/java/com/business/common/aop/RoleCheckAspect.java
  user/src/main/java/com/business/user/user/application/service/UserService.java
  user/src/main/java/com/business/user/user/presentation/controller/UserController.java
Labels: 🩹 fix

#262 bugfix: 업체 조회 오류 수정 및 aop 적용
  company/src/main/java/com/business/company/application/service/CompanyService.java
  company/src/main/java/com/business/company/domain/entity/Company.java
  company/src/main/java/com/business/company/domain/repository/CompanyRepository.java
  company/src/main/java/com/business/company/infrastructure/repository/CompanyJpaRepository.java
  company/src/main/java/com/business/company/infrastructure/repository/CompanyRepositoryImpl.java
  company/src/main/java/com/business/company/presentation/CompanyController.java
  company/src/test/resources/test/CreateCompany.http
  company/src/test/resources/test/DeleteCompany.http
  company/src/test/resources/test/SearchCompany.http
  product/src/main/java/com/business/product/inventory/presentation/InventoryController.java
  product/src/main/java/com/business/product/product/presentation/ProductController.java
Labels: 🩹 fix

#268 bugfix: 권한 체크를 위한 사용자 정보 헤더(userId, role) 추가
  delivery/src/main/java/com/business/delivery/application/service/DeliveryService.java
  delivery/src/main/java/com/business/delivery/infrastructure/client/HubClient.java
  delivery/src/main/java/com/business/delivery/infrastructure/client/OrderClient.java
  delivery/src/main/java/com/business/delivery/infrastructure/client/UserClient.java
  delivery/src/main/java/com/business/delivery/presentation/controller/DeliveryController.java
  delivery/src/test/java/com/business/delivery/application/service/DeliveryServiceCancelTest.java
  delivery/src/test/java/com/business/delivery/application/service/DeliveryServiceStatusTest.java
  user/src/main/java/com/business/user/deliverydriver/application/service/DeliveryDriverService.java
  user/src/main/java/com/business/user/deliverydriver/infrastructure/client/DeliveryClient.java
  user/src/main/java/com/business/user/deliverydriver/infrastructure/client/HubClient.java
  user/src/main/java/com/business/user/deliverydriver/presentation/controller/DeliveryDriverController.java
  user/src/test/java/com/business/user/deliverydriver/application/service/DeliveryDriverServiceCancelTest.java
  user/src/test/java/com/business/user/deliverydriver/application/service/DeliveryDriverServiceStatusTest.java
Labels: 🩹 fix

#269 refactor: 논리 삭제 기준을 deletedAt에서 deletedBy로 변경
  delivery/src/main/java/com/business/delivery/infrastructure/repository/DeliveryJpaRepository.java
  delivery/src/main/java/com/business/delivery/infrastructure/repository/DeliveryRepositoryImpl.java
  user/src/main/java/com/business/user/deliverydriver/infrastructure/repository/DeliveryDriverJpaRepository.java
  user/src/main/java/com/business/user/deliverydriver/infrastructure/repository/DeliveryDriverRepositoryImpl.java
  user/src/test/java/com/business/user/deliverydriver/infrastructure/repository/DeliveryDriverRepositoryTest.java
Labels: 🩹 fix

#271 fix: 통합 후 테스트하며 발생하는 오류 수정했습니다.
  .gitignore
  ai/build.gradle
  ai/src/main/resources/application.yml
  auth/src/main/resources/application.yml
  auth/src/test/resources/AuthClientTest.http
  common/src/main/resources/application.yml
  company/src/main/resources/application.yml
  company/src/test/resources/test/CreateCompany.http
  company/src/test/resources/test/DeleteCompany.http
  delivery/src/main/java/com/business/delivery/application/dto/mapper/DeliveryRequestMapper.java
  delivery/src/main/java/com/business/delivery/application/service/DeliveryService.java
  delivery/src/main/java/com/business/delivery/domain/entity/Delivery.java
  delivery/src/main/java/com/business/delivery/infrastructure/client/HubClient.java
  delivery/src/main/java/com/business/delivery/infrastructure/client/OrderClient.java
  delivery/src/main/java/com/business/delivery/infrastructure/client/UserClient.java
  delivery/src/main/java/com/business/delivery/infrastructure/dto/response/HubIdResponseDto.java
  delivery/src/main/java/com/business/delivery/infrastructure/repository/DeliveryRepositoryImpl.java
  delivery/src/main/java/com/business/delivery/presentation/controller/DeliveryController.java
  delivery/src/main/resources/application.yml
  delivery/src/test/java/com/business/delivery/application/service/DeliveryServiceStatusTest.java
  delivery/src/test/resources/test/DeliveryTest.http
  docker-compose.yml
  eureka/src/main/resources/application.yml
  gateway/src/main/resources/application.yml
  hub/src/main/java/com/business/hub/infrastructure/client/DeliveryServiceClient.java
  hub/src/main/java/com/business/hub/infrastructure/client/OrderServiceClient.java
  hub/src/main/java/com/business/hub/infrastructure/client/ProductServiceClient.java
  hub/src/main/java/com/business/hub/infrastructure/configuration/FeginClientConfig.java
  hub/src/main/java/com/business/hub/infrastructure/configuration/HubConfig.java
  hub/src/main/java/com/business/hub/infrastructure/configuration/HubMovementConfig.java
  hub/src/main/resources/application.yml
  hub/src/test/resources/test/GetHubClient.http
  hub/src/test/resources/test/GetHubMovementClientTest.http
  hub/src/test/resources/test/HubMovementRegistertest.http
  order/src/main/java/com/business/order/application/service/OrderService.java
  order/src/main/java/com/business/order/domain/entity/Order.java
  order/src/main/java/com/business/order/infrastructure/client/DeliveryFeignClient.java
  order/src/main/java/com/business/order/presentaion/OrderController.java
  order/src/main/resources/application.yml
  order/src/test/resources/test/CreateOrderClient.http
  order/src/test/resources/test/GetOrderClient.http
  order/src/test/resources/test/updateOrderClient.http
  product/src/main/resources/application.yml
  product/src/test/resources/test/CreateProduct.http
  product/src/test/resources/test/SearchProduct.http
  product/src/test/resources/test/UpdateInventory.http
  slack/src/main/resources/application.yml
  user/src/main/java/com/business/user/deliverydriver/application/dto/mapper/DeliveryDriverResponseMapper.java
  user/src/main/java/com/business/user/deliverydriver/application/dto/request/StatusUpdateRequestDto.java
  user/src/main/java/com/business/user/deliverydriver/application/dto/response/AssignDeliveryDriverResponseDto.java
  user/src/main/java/com/business/user/deliverydriver/application/service/DeliveryDriverService.java
  user/src/main/java/com/business/user/deliverydriver/domain/entity/DeliveryDriver.java
  user/src/main/java/com/business/user/deliverydriver/domain/entity/DriverStatus.java
  user/src/main/java/com/business/user/deliverydriver/infrastructure/client/DeliveryClient.java
  user/src/main/java/com/business/user/deliverydriver/infrastructure/client/HubClient.java
  user/src/main/java/com/business/user/deliverydriver/infrastructure/dto/response/DeliveryResponseWrapperDto.java
  user/src/main/java/com/business/user/deliverydriver/presentation/controller/DeliveryDriverController.java
  user/src/main/resources/application.yml
  user/src/test/resources/test/DeliveryDriverTest.http
Labels: 🩹 fix
